# Generated by Django 4.1.3 on 2022-12-05 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_desc',
            field=models.CharField(default=datetime.datetime(2022, 12, 5, 7, 13, 42, 699729, tzinfo=datetime.timezone.utc), max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=datetime.datetime(2022, 12, 5, 7, 13, 51, 33894, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
