# Generated by Django 4.1.3 on 2022-12-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='publish_date',
        ),
    ]
